#!/bin/bash

#permit max QUOTA bytes from protocol tcp and port 80 (ROUTED TRAFFIC, we are the ROUTER)
#traffic is generated by a server inside our lan. This is downloaded traffic by Internet clients from our server.


####EDIT the values below#########
PROTOCOL="tcp"
PORT="80"
#1GB
QUOTA="1000000000"
#this is the outgoing interface
INT="eth0"

###DO NOT EDIT BELOW THIS LINE
iptables -A FORWARD -o eth0 -p $PROTOCOL --sport $PORT -m quota --quota $QUOTA -j ACCEPT
iptables -A FORWARD -o eth0 -p $PROTOCOL --sport $PORT -j DROP
